class Curriculum:
    BEGINNER_PATH = [
        "Intervals",
        "Major Triads",
        "Minor Triads",
        "Diminished Triads",
        "Suspended Chords",
        "Major 7th Chords",
        "Minor 7th Chords",
        "Dominant 7th Chords"
    ]

    ADVANCED_PATH = [
        "Circle of 5ths",
        "Half-Diminished 7th",
        "Fully Diminished 7th"
    ]

    DESCRIPTIONS = {
        'Intervals': "The building blocks of melody and harmony. Recognizing distance between notes is the first step to ear training.",
        "Major Triads": "The most common chord in Western music. Sounds happy, stable, and resolved.",
        "Minor Triads": "The emotional counterpart to Major. Sounds sad, serious, or introspective.",
        "Diminished Triads": "Tense and unstable. Often used to pass between other chords or in horror scores.",
        "Suspended Chords": "Replaces the 3rd with a 2nd or 4th. Sounds open, airy, and floats without resolving immediately.",
        "Major 7th Chords": "A major triad with a major 7th on top. The sound of Jazz, Lo-Fi, and Neo-Soul. Dreamy and nostalgic.",
        "Minor 7th Chords": "A minor triad with a minor 7th. Mellow, cool, and sophisticated. The foundation of R&B and Jazz.",
        "Dominant 7th Chords": "A major triad with a minor 7th. The engine of functional harmony. It wants to pull you home to the Tonic.",
        "Half-Diminished 7th": "Also called 'Minor 7 flat 5'. Dark, mysterious, and tragic. Essential for minor key jazz progressions.",
        "Fully Diminished 7th": "A stack of minor 3rds. Symmetrical, ambiguous, and extremely tense. Used for dramatic effect.",
        "Circle of 5ths": "The map of music theory. Shows how keys relate to each other. Essential for modulation and songwriting."
    }
    
    CHALLENGES = {
        "Intervals": [
            {"type": "interval", "root": "C4", "semitones": 4, "instruction": "Play a C Major 3rd", 
             "context": "The 'Happy' interval. Opening notes of 'When the Saints Go Marching In'."},
            {"type": "interval", "root": "C4", "semitones": 7, "instruction": "Play a C Perfect 5th", 
             "context": "The 'Power' interval. Opening notes of 'Star Wars' main theme and 'Twinkle Twinkle Little Star'."},
            {"type": "interval", "root": "A3", "semitones": 3, "instruction": "Play an A Minor 3rd", 
             "context": "The 'Sad' interval. Opening notes of 'Greensleeves' and a Brahms Lullaby."},
            {"type": "interval", "root": "G3", "semitones": 5, "instruction": "Play a G Perfect 4th", 
             "context": "The 'Call' interval. Opening notes of 'Here Comes the Bride' (Wagner)."},
            {"type": "interval", "root": "D4", "semitones": 2, "instruction": "Play a D Major 2nd", 
             "context": "A whole step. The start of 'Happy Birthday'."},
            {"type": "interval", "root": "E4", "semitones": 1, "instruction": "Play an E Minor 2nd", 
             "context": "The 'Jaws' theme. Extremely dissonant and tense."},
            {"type": "interval", "root": "F3", "semitones": 12, "instruction": "Play an F Octave", 
             "context": "Same note, higher pitch. Opening of 'Somewhere Over the Rainbow'."},
            {"type": "interval", "root": "B3", "semitones": 6, "instruction": "Play a B Tritone", 
             "context": "The 'Devil in Music' (Diabolus in Musica). Opening of 'The Simpsons' theme."},
            {"type": "interval", "root": "C4", "semitones": 11, "instruction": "Play a C Major 7th Interval", 
             "context": "Very dissonant but dreamy. Opening of 'Take on Me' (A-ha) chorus interval."},
            {"type": "interval", "root": "D4", "semitones": 10, "instruction": "Play a D Minor 7th Interval", 
             "context": "Opening interval of the original 'Star Trek' theme."}
        ],
        "Major Triads": [
            {"type": "triad", "root": "C4", "formula_key": "maj", "instruction": "Play a C Major Triad", 
             "context": "Classic Pop: 'Let It Be' (Beatles) starts on C Major."},
            {"type": "triad", "root": "G3", "formula_key": "maj", "instruction": "Play a G Major Triad", 
             "context": "Rock Anthem: 'Sweet Home Alabama' uses D, C, G."},
            {"type": "triad", "root": "D4", "formula_key": "maj", "instruction": "Play a D Major Triad", 
             "context": "Pop/Country: 'Bad Moon Rising' (CCR) centers on D Major."},
            {"type": "triad", "root": "A3", "formula_key": "maj", "instruction": "Play an A Major Triad", 
             "context": "Classic Rock: 'Free Fallin' (Tom Petty) relies heavily on F and A shapes."},
            {"type": "triad", "root": "E4", "formula_key": "maj", "instruction": "Play an E Major Triad", 
             "context": "Blues/Rock: Key to many Jimi Hendrix songs (often tuned down)."},
            {"type": "triad", "root": "F3", "formula_key": "maj", "instruction": "Play an F Major Triad", 
             "context": "Ballad: 'Imagine' (John Lennon) oscillates between C and F."},
            {"type": "triad", "root": "Bb3", "formula_key": "maj", "instruction": "Play a Bb Major Triad", 
             "context": "R&B/Soul: Common key for horn sections and James Brown tracks."},
            {"type": "triad", "root": "Eb4", "formula_key": "maj", "instruction": "Play an Eb Major Triad", 
             "context": "Gospel: Often used in church music for a rich, warm sound."},
            {"type": "triad", "root": "Ab3", "formula_key": "maj", "instruction": "Play an Ab Major Triad", 
             "context": "Pop: 'Empire State of Mind' (Jay-Z/Alicia Keys) features F# and B (relative)."},
            {"type": "triad", "root": "B3", "formula_key": "maj", "instruction": "Play a B Major Triad", 
             "context": "Bright and piercing. Used in 'September' (Earth, Wind & Fire)."}
        ],
        "Minor Triads": [
            {"type": "triad", "root": "A3", "formula_key": "min", "instruction": "Play an A Minor Triad", 
             "context": "Pop/Rock: 'Stairway to Heaven' (Led Zeppelin) starts here."},
            {"type": "triad", "root": "E4", "formula_key": "min", "instruction": "Play an E Minor Triad", 
             "context": "Metal: The standard tuning for Metallica (e.g., 'Enter Sandman')."},
            {"type": "triad", "root": "D4", "formula_key": "min", "instruction": "Play a D Minor Triad", 
             "context": "The 'Saddest Key' (Spinal Tap). Hans Zimmer uses Dm for 'The Dark Knight'."},
            {"type": "triad", "root": "G3", "formula_key": "min", "instruction": "Play a G Minor Triad", 
             "context": "Neo-Classical: Mozart's Symphony No. 40."},
            {"type": "triad", "root": "C4", "formula_key": "min", "instruction": "Play a C Minor Triad", 
             "context": "Epic/Heroic: Beethoven's 5th Symphony."},
            {"type": "triad", "root": "F3", "formula_key": "min", "instruction": "Play an F Minor Triad", 
             "context": "Pop Ballad: 'Hello' (Adele) is in F Minor."},
            {"type": "triad", "root": "B3", "formula_key": "min", "instruction": "Play a B Minor Triad", 
             "context": "Pink Floyd: 'Comfortably Numb' uses Bm for the solos."},
            {"type": "triad", "root": "F#3", "formula_key": "min", "instruction": "Play an F# Minor Triad", 
             "context": "Disco/Funk: 'Get Lucky' (Daft Punk) revolves around F#m."},
            {"type": "triad", "root": "C#4", "formula_key": "min", "instruction": "Play a C# Minor Triad", 
             "context": "Pop: 'Shape of You' (Ed Sheeran) uses C#m."},
            {"type": "triad", "root": "Eb4", "formula_key": "min", "instruction": "Play an Eb Minor Triad", 
             "context": "Jazz: 'Take Five' (Dave Brubeck) vamp."}
        ],
        "Diminished Triads": [
            {"type": "triad", "root": "B3", "formula_key": "dim", "instruction": "Play a B Diminished Triad", 
             "context": "Classical: The leading tone chord in C Major. Resolves to C."},
            {"type": "triad", "root": "F#3", "formula_key": "dim", "instruction": "Play an F# Diminished Triad", 
             "context": "Used in G Minor progressions to pull to G."},
            {"type": "triad", "root": "C#4", "formula_key": "dim", "instruction": "Play a C# Diminished Triad", 
             "context": "Passing chord in D Major harmonies."},
            {"type": "triad", "root": "G#3", "formula_key": "dim", "instruction": "Play a G# Diminished Triad", 
             "context": "Horror: Used to create instant suspense."},
            {"type": "triad", "root": "D#4", "formula_key": "dim", "instruction": "Play a D# Diminished Triad", 
             "context": "Bridge chords in Jazz standards like 'All The Things You Are'."},
            {"type": "triad", "root": "A3", "formula_key": "dim", "instruction": "Play an A Diminished Triad", 
             "context": "Dark/Tense transitions in film scores."},
            {"type": "triad", "root": "E4", "formula_key": "dim", "instruction": "Play an E Diminished Triad", 
             "context": "Leading chord to F Major."},
            {"type": "triad", "root": "C4", "formula_key": "dim", "instruction": "Play a C Diminished Triad", 
             "context": "Dissonant passing chord."},
            {"type": "triad", "root": "F4", "formula_key": "dim", "instruction": "Play an F Diminished Triad", 
             "context": "Often found in Gb Major context as the vii°."},
            {"type": "triad", "root": "G4", "formula_key": "dim", "instruction": "Play a G Diminished Triad", 
             "context": "Used in Ab Major context."}
        ],
        "Suspended Chords": [
            {"type": "triad", "root": "C4", "formula_key": "sus4", "instruction": "Play a C Sus4 Chord", 
             "context": "Pop: 'Crazy Little Thing Called Love' (Queen) intro."},
            {"type": "triad", "root": "C4", "formula_key": "sus2", "instruction": "Play a C Sus2 Chord", 
             "context": "Rock: 'Summer of 69' (Bryan Adams) main riff feel."},
            {"type": "triad", "root": "G3", "formula_key": "sus4", "instruction": "Play a G Sus4 Chord", 
             "context": "Folk: 'A Hard Day's Night' opening chord features a sus4."},
            {"type": "triad", "root": "G3", "formula_key": "sus2", "instruction": "Play a G Sus2 Chord", 
             "context": "Anthem: 'What's Up' (4 Non Blondes)."},
            {"type": "triad", "root": "D4", "formula_key": "sus4", "instruction": "Play a D Sus4 Chord", 
             "context": "Classic Rock: 'Pinball Wizard' (The Who) strumming pattern."},
            {"type": "triad", "root": "D4", "formula_key": "sus2", "instruction": "Play a D Sus2 Chord", 
             "context": "Ballad: 'Free Fallin' (Tom Petty)."},
            {"type": "triad", "root": "A3", "formula_key": "sus4", "instruction": "Play an A Sus4 Chord", 
             "context": "80s Rock: 'Jack & Diane' (Mellencamp)."},
            {"type": "triad", "root": "A3", "formula_key": "sus2", "instruction": "Play an A Sus2 Chord", 
             "context": "Police: 'Message in a Bottle' uses stacked sus2 shapes."},
            {"type": "triad", "root": "F4", "formula_key": "sus4", "instruction": "Play an F Sus4 Chord", 
             "context": "Gospel: Common ending cadence (Amen Plagal)."},
            {"type": "triad", "root": "F4", "formula_key": "sus2", "instruction": "Play an F Sus2 Chord", 
             "context": "Modern Pop: Used in progressions for 'Someone Like You' (Adele)."}
        ],
        "Major 7th Chords": [
            {"type": "triad", "root": "C4", "formula_key": "maj7", "instruction": "Play a C Major 7th", 
             "context": "Lo-Fi/Chill: The 'Gymnopedie No.1' (Satie) feel."},
            {"type": "triad", "root": "F3", "formula_key": "maj7", "instruction": "Play an F Major 7th", 
             "context": "Pop: 'Don't Know Why' (Norah Jones)."},
            {"type": "triad", "root": "G3", "formula_key": "maj7", "instruction": "Play a G Major 7th", 
             "context": "Jazz: 'Misty' (Erroll Garner) often lands here."},
            {"type": "triad", "root": "Bb3", "formula_key": "maj7", "instruction": "Play a Bb Major 7th", 
             "context": "Soul: 'What's Going On' (Marvin Gaye)."},
            {"type": "triad", "root": "Eb4", "formula_key": "maj7", "instruction": "Play an Eb Major 7th", 
             "context": "R&B: 'Best Part' (Daniel Caesar)."},
            {"type": "triad", "root": "Ab3", "formula_key": "maj7", "instruction": "Play an Ab Major 7th", 
             "context": "Disco: 'I Will Survive' verse chords."},
            {"type": "triad", "root": "D4", "formula_key": "maj7", "instruction": "Play a D Major 7th", 
             "context": "City Pop: Common in Japanese 80s Pop (Plastic Love)."},
            {"type": "triad", "root": "A3", "formula_key": "maj7", "instruction": "Play an A Major 7th", 
             "context": "Rock: 'Under the Bridge' (RHCP) outro."},
            {"type": "triad", "root": "E4", "formula_key": "maj7", "instruction": "Play an E Major 7th", 
             "context": "Indie: 'Sanctuary' (Joji)."},
            {"type": "triad", "root": "Gb3", "formula_key": "maj7", "instruction": "Play a Gb Major 7th", 
             "context": "Neo-Soul: Common key for Moonchild or Hiatus Kaiyote."}
        ],
        "Minor 7th Chords": [
            {"type": "triad", "root": "D4", "formula_key": "min7", "instruction": "Play a D Minor 7th", 
             "context": "Funk: 'Get Down On It' (Kool & The Gang)."},
            {"type": "triad", "root": "G3", "formula_key": "min7", "instruction": "Play a G Minor 7th", 
             "context": "Jazz: 'Autumn Leaves' II chord."},
            {"type": "triad", "root": "C4", "formula_key": "min7", "instruction": "Play a C Minor 7th", 
             "context": "Hip Hop: 'Nujabes' style piano samples."},
            {"type": "triad", "root": "F3", "formula_key": "min7", "instruction": "Play an F Minor 7th", 
             "context": "House: Deep House chords often parallel Fmin7."},
            {"type": "triad", "root": "A3", "formula_key": "min7", "instruction": "Play an A Minor 7th", 
             "context": "Rock: 'Let It Be' (Beatles) uses Am7 descending."},
            {"type": "triad", "root": "E4", "formula_key": "min7", "instruction": "Play an E Minor 7th", 
             "context": "Bossa Nova: 'Girl From Ipanema' vamp."},
            {"type": "triad", "root": "B3", "formula_key": "min7", "instruction": "Play a B Minor 7th", 
             "context": "Pop: 'Just the Way You Are' (Bruno Mars)."},
            {"type": "triad", "root": "F#3", "formula_key": "min7", "instruction": "Play an F# Minor 7th", 
             "context": "R&B: 'No Scrubs' (TLC) loop."},
            {"type": "triad", "root": "C#4", "formula_key": "min7", "instruction": "Play a C# Minor 7th", 
             "context": "Pop: 'Sunday Morning' (Maroon 5)."},
            {"type": "triad", "root": "Bb3", "formula_key": "min7", "instruction": "Play a Bb Minor 7th", 
             "context": "Jazz: 'Blue Bossa' opening chord."}
        ],
        "Dominant 7th Chords": [
            {"type": "triad", "root": "G3", "formula_key": "dom7", "instruction": "Play a G Dominant 7th (G7)", 
             "context": "Blues: The V chord in C Blues."},
            {"type": "triad", "root": "C4", "formula_key": "dom7", "instruction": "Play a C Dominant 7th (C7)", 
             "context": "Funk: 'Brick House' (Commodores)."},
            {"type": "triad", "root": "F3", "formula_key": "dom7", "instruction": "Play an F Dominant 7th (F7)", 
             "context": "Beatles: 'Twist and Shout' (IV7 chord)."},
            {"type": "triad", "root": "Bb3", "formula_key": "dom7", "instruction": "Play a Bb Dominant 7th (Bb7)", 
             "context": "Jazz Blues: 'Tenor Madness' (Sonny Rollins)."},
            {"type": "triad", "root": "Eb4", "formula_key": "dom7", "instruction": "Play an Eb Dominant 7th (Eb7)", 
             "context": "Stevie Wonder: 'Superstition' vamp."},
            {"type": "triad", "root": "Ab3", "formula_key": "dom7", "instruction": "Play an Ab Dominant 7th (Ab7)", 
             "context": "R&B: Secondary dominant in Eb Major."},
            {"type": "triad", "root": "D4", "formula_key": "dom7", "instruction": "Play a D Dominant 7th (D7)", 
             "context": "Folk: 'Blowin' in the Wind' (Dylan)."},
            {"type": "triad", "root": "A3", "formula_key": "dom7", "instruction": "Play an A Dominant 7th (A7)", 
             "context": "Rockabilly: 'Blue Suede Shoes'."},
            {"type": "triad", "root": "E4", "formula_key": "dom7", "instruction": "Play an E Dominant 7th (E7)", 
             "context": "Blues: The turnaround chord in A Blues."},
            {"type": "triad", "root": "B3", "formula_key": "dom7", "instruction": "Play a B Dominant 7th (B7)", 
             "context": "Beatles: 'I Saw Her Standing There' (V chord)."}
        ],
        "Half-Diminished 7th": [
            {"type": "triad", "root": "B3", "formula_key": "m7b5", "instruction": "Play a B Half-Diminished (Bø7)", 
             "context": "Jazz: 'Autumn Leaves' opening chord (in Gm)."},
            {"type": "triad", "root": "E4", "formula_key": "m7b5", "instruction": "Play an E Half-Diminished (Eø7)", 
             "context": "Minor 2-5-1 in D Minor."},
            {"type": "triad", "root": "A3", "formula_key": "m7b5", "instruction": "Play an A Half-Diminished (Aø7)", 
             "context": "Standard: 'Stella by Starlight' first chord."},
            {"type": "triad", "root": "D4", "formula_key": "m7b5", "instruction": "Play a D Half-Diminished (Dø7)", 
             "context": "Minor 2-5-1 in C Minor (Dø7 - G7 - Cm7)."},
            {"type": "triad", "root": "G3", "formula_key": "m7b5", "instruction": "Play a G Half-Diminished (Gø7)", 
             "context": "Minor 2-5-1 in F Minor."},
            {"type": "triad", "root": "C4", "formula_key": "m7b5", "instruction": "Play a C Half-Diminished (Cø7)", 
             "context": "Jazz: 'Blue Bossa' (transition to Db major)."},
            {"type": "triad", "root": "F#3", "formula_key": "m7b5", "instruction": "Play an F# Half-Diminished (F#ø7)", 
             "context": "Minor 2-5-1 in E Minor."},
            {"type": "triad", "root": "C#4", "formula_key": "m7b5", "instruction": "Play a C# Half-Diminished (C#ø7)", 
             "context": "Jazz: 'Night and Day' (Cole Porter) uses this movement."},
            {"type": "triad", "root": "F4", "formula_key": "m7b5", "instruction": "Play an F Half-Diminished (Fø7)", 
             "context": "Complex passing chord in ballads."},
            {"type": "triad", "root": "Bb3", "formula_key": "m7b5", "instruction": "Play a Bb Half-Diminished (Bbø7)", 
             "context": "Minor 2-5-1 in Ab Minor."}
        ],
        "Fully Diminished 7th": [
            {"type": "triad", "root": "B3", "formula_key": "dim7", "instruction": "Play a B Fully Diminished (B°7)", 
             "context": "Classical: Resolves strongly to C Major."},
            {"type": "triad", "root": "C#4", "formula_key": "dim7", "instruction": "Play a C# Fully Diminished (C#°7)", 
             "context": "Horror: 'Phantom of the Opera' (Descending chromatic dim7s)."},
            {"type": "triad", "root": "D#4", "formula_key": "dim7", "instruction": "Play a D# Fully Diminished (D#°7)", 
             "context": "Silent Film: 'Villain ties damsel to tracks'."},
            {"type": "triad", "root": "E4", "formula_key": "dim7", "instruction": "Play an E Fully Diminished (E°7)", 
             "context": "Jazz: Passing chord between Em7 and Dm7."},
            {"type": "triad", "root": "F#3", "formula_key": "dim7", "instruction": "Play an F# Fully Diminished (F#°7)", 
             "context": "Gospel: Passing chord to G/B."},
            {"type": "triad", "root": "G#3", "formula_key": "dim7", "instruction": "Play a G# Fully Diminished (G#°7)", 
             "context": "Commonly resolves to A Minor."},
            {"type": "triad", "root": "A#3", "formula_key": "dim7", "instruction": "Play an A# Fully Diminished (A#°7)", 
             "context": "Passing chord in B Minor."},
            {"type": "triad", "root": "C4", "formula_key": "dim7", "instruction": "Play a C Fully Diminished (C°7)", 
             "context": "Jazz: 'Corcovado' (Jobim) uses dim7 tension."},
            {"type": "triad", "root": "D4", "formula_key": "dim7", "instruction": "Play a D Fully Diminished (D°7)", 
             "context": "Blues: 'Stormy Monday' (turnaround chord)."},
            {"type": "triad", "root": "F4", "formula_key": "dim7", "instruction": "Play an F Fully Diminished (F°7)", 
             "context": "Chromatic passing chord."}
        ],
        "Circle of 5ths": [
            {"type": "sequence", "notes": ["C4", "F4", "Bb3"], "instruction": "Circle: Play C -> F -> Bb (Descending 5ths)", 
             "context": "The standard Jazz motion (II-V-I)."},
            {"type": "sequence", "notes": ["Bb3", "Eb4", "Ab3"], "instruction": "Circle: Play Bb -> Eb -> Ab", 
             "context": "Common key change in Gospel music."},
            {"type": "sequence", "notes": ["Ab3", "Db4", "Gb3"], "instruction": "Circle: Play Ab -> Db -> Gb", 
             "context": "R&B bridge progressions."},
            {"type": "sequence", "notes": ["Gb3", "B3", "E4"], "instruction": "Circle: Play Gb -> B -> E", 
             "context": "Moving from 'Dark' keys to 'Bright' keys."},
            {"type": "sequence", "notes": ["E4", "A3", "D4"], "instruction": "Circle: Play E -> A -> D", 
             "context": "Classic Rock 'Hey Joe' (Hendrix) progression."},
            {"type": "sequence", "notes": ["D4", "G3", "C4"], "instruction": "Circle: Play D -> G -> C", 
             "context": "The 'Amen Cadence' resolution."},
            {"type": "sequence", "notes": ["C4", "G3", "D4"], "instruction": "Reverse Circle: C -> G -> D (Ascending 5ths)", 
             "context": "Folk/Pop: 'Hey Jude' (Beatles)."},
            {"type": "sequence", "notes": ["D4", "A3", "E4"], "instruction": "Reverse Circle: D -> A -> E", 
             "context": "Country roads take me home."},
            {"type": "sequence", "notes": ["E4", "B3", "F#3"], "instruction": "Reverse Circle: E -> B -> F#", 
             "context": "Brightening the key center."},
            {"type": "sequence", "notes": ["F#3", "C#4", "G#3"], "instruction": "Reverse Circle: F# -> C# -> G#", 
             "context": "Modulating to sharper keys."}
        ]
    }