class Curriculum:
    BEGINNER_PATH = [
        "Intervals",
        "Major Triads",
        "Minor Triads",
        "Diminished Triads",
        "Suspended Chords",
        "Major 7th Chords",
        "Minor 7th Chords",
        "Dominant 7th Chords"
    ]

    ADVANCED_PATH = [
        "Circle of 5ths",
        "Half-Diminished 7th",
        "Fully Diminished 7th"
    ]

    DESCRIPTIONS = {
        'Intervals': "The building blocks of melody. Recognizing distance between notes is the first step to ear training.",
        "Major Triads": "The most common chord in Western music. Sounds happy, stable, and resolved.",
        "Minor Triads": "The emotional counterpart to Major. Sounds sad, serious, or introspective.",
        "Diminished Triads": "Tense and unstable. Used to pass between other chords or create suspense.",
        "Suspended Chords": "Replaces the 3rd with a 2nd or 4th. Sounds open, airy, and 'suspended' in mid-air.",
        "Major 7th Chords": "A major triad with a major 7th. The sound of Jazz, Lo-Fi, and Dream Pop.",
        "Minor 7th Chords": "A minor triad with a minor 7th. Mellow, cool, and sophisticated. The foundation of R&B.",
        "Dominant 7th Chords": "The engine of harmony. Contains a Tritone that wants to pull you home to the Tonic.",
        "Half-Diminished 7th": "Also called 'Minor 7 flat 5'. Dark, romantic, and tragic. Essential for minor key Jazz.",
        "Fully Diminished 7th": "A stack of minor 3rds. Symmetrical, ambiguous, and extremely tense. The 'Villain' chord.",
        "Circle of 5ths": "The map of music theory. Shows how keys relate to each other. Essential for songwriting."
    }
    
    CHALLENGES = {
        "Intervals": [
            {"type": "interval", "root": "C4", "semitones": 4, "instruction": "Play a C Major 3rd", 
             "context": "The 'Happy' interval. Opening notes of 'When the Saints Go Marching In' (Oh-When)."},
            {"type": "interval", "root": "C4", "semitones": 7, "instruction": "Play a C Perfect 5th", 
             "context": "The 'Power' interval. Opening notes of 'Star Wars' (Main Theme) and 'Twinkle Twinkle'."},
            {"type": "interval", "root": "A3", "semitones": 3, "instruction": "Play an A Minor 3rd", 
             "context": "The 'Sad' interval. Opening notes of 'Greensleeves' and Brahms' Lullaby."},
            {"type": "interval", "root": "G3", "semitones": 5, "instruction": "Play a G Perfect 4th", 
             "context": "The 'Call' interval. Opening notes of 'Here Comes the Bride' (Wagner) and 'Amazing Grace'."},
            {"type": "interval", "root": "D4", "semitones": 2, "instruction": "Play a D Major 2nd", 
             "context": "A whole step. The start of 'Happy Birthday' (Hap-py)."},
            {"type": "interval", "root": "E4", "semitones": 1, "instruction": "Play an E Minor 2nd", 
             "context": "The 'Jaws' theme. Extremely dissonant and tense half-step movement."},
            {"type": "interval", "root": "F3", "semitones": 12, "instruction": "Play an F Octave", 
             "context": "Same note, higher pitch. Opening jump of 'Somewhere Over the Rainbow'."},
            {"type": "interval", "root": "B3", "semitones": 6, "instruction": "Play a B Tritone", 
             "context": "The 'Devil in Music'. Opening interval of 'The Simpsons' theme (The-Simp)."},
            {"type": "interval", "root": "C4", "semitones": 11, "instruction": "Play a C Major 7th Interval", 
             "context": "Very dissonant but dreamy. The chorus leap in 'Take On Me' (Take-On) is a Major 7th."},
            {"type": "interval", "root": "D4", "semitones": 10, "instruction": "Play a D Minor 7th Interval", 
             "context": "Opening interval of the original 'Star Trek' theme (There's a place...)."}
        ],
        "Major Triads": [
            {"type": "triad", "root": "C4", "formula_key": "maj", "instruction": "Play a C Major Triad", 
             "context": "Classic Pop: 'Let It Be' (Beatles) starts firmly on C Major."},
            {"type": "triad", "root": "G3", "formula_key": "maj", "instruction": "Play a G Major Triad", 
             "context": "Rock Anthem: 'Sweet Home Alabama' riff revolves around D-C-G."},
            {"type": "triad", "root": "D4", "formula_key": "maj", "instruction": "Play a D Major Triad", 
             "context": "Pop/Rock: 'Bad Moon Rising' (CCR) centers on the D Major chord."},
            {"type": "triad", "root": "A3", "formula_key": "maj", "instruction": "Play an A Major Triad", 
             "context": "Reggae: 'Three Little Birds' (Bob Marley) is in A Major."},
            {"type": "triad", "root": "E4", "formula_key": "maj", "instruction": "Play an E Major Triad", 
             "context": "Blues/Rock: The 'Hendrix Chord' foundation. Key of 'Purple Haze'."},
            {"type": "triad", "root": "F3", "formula_key": "maj", "instruction": "Play an F Major Triad", 
             "context": "Ballad: 'Imagine' (John Lennon) oscillates between C and F."},
            {"type": "triad", "root": "Bb3", "formula_key": "maj", "instruction": "Play a Bb Major Triad", 
             "context": "Soul: Common horn key. 'I Got You (I Feel Good)' (James Brown) jam."},
            {"type": "triad", "root": "Eb4", "formula_key": "maj", "instruction": "Play an Eb Major Triad", 
             "context": "Gospel: Often used in church music for a warm, rich tone."},
            {"type": "triad", "root": "Ab3", "formula_key": "maj", "instruction": "Play an Ab Major Triad", 
             "context": "Pop Anthem: 'Somebody to Love' (Queen) starts on Ab."},
            {"type": "triad", "root": "B3", "formula_key": "maj", "instruction": "Play a B Major Triad", 
             "context": "Funk: 'September' (Earth, Wind & Fire) chorus hits Bmaj7/B."}
        ],
        "Minor Triads": [
            {"type": "triad", "root": "A3", "formula_key": "min", "instruction": "Play an A Minor Triad", 
             "context": "Rock Ballad: 'Stairway to Heaven' (Led Zeppelin) intro arpeggio."},
            {"type": "triad", "root": "E4", "formula_key": "min", "instruction": "Play an E Minor Triad", 
             "context": "Metal: 'Enter Sandman' (Metallica) relies on the open E string power."},
            {"type": "triad", "root": "D4", "formula_key": "min", "instruction": "Play a D Minor Triad", 
             "context": "Dramatic: Hans Zimmer's 'The Dark Knight' score often sits in Dm."},
            {"type": "triad", "root": "G3", "formula_key": "min", "instruction": "Play a G Minor Triad", 
             "context": "Classical: Mozart's Symphony No. 40 is famous for its Gm urgency."},
            {"type": "triad", "root": "C4", "formula_key": "min", "instruction": "Play a C Minor Triad", 
             "context": "Epic: Beethoven's 5th Symphony ('Fate knocking')."},
            {"type": "triad", "root": "F3", "formula_key": "min", "instruction": "Play an F Minor Triad", 
             "context": "Pop Ballad: 'Hello' (Adele) verses are in F Minor."},
            {"type": "triad", "root": "B3", "formula_key": "min", "instruction": "Play a B Minor Triad", 
             "context": "Prog Rock: 'Comfortably Numb' (Pink Floyd) solos are in Bm."},
            {"type": "triad", "root": "F#3", "formula_key": "min", "instruction": "Play an F# Minor Triad", 
             "context": "Disco: 'Get Lucky' (Daft Punk) loops Bm-D-F#m-E."},
            {"type": "triad", "root": "C#4", "formula_key": "min", "instruction": "Play a C# Minor Triad", 
             "context": "Modern Pop: 'Shape of You' (Ed Sheeran) loop uses C#m."},
            {"type": "triad", "root": "Eb4", "formula_key": "min", "instruction": "Play an Eb Minor Triad", 
             "context": "Jazz: 'Take Five' (Dave Brubeck) vamp is in Ebm."}
        ],
        "Diminished Triads": [
            {"type": "triad", "root": "B3", "formula_key": "dim", "instruction": "Play a B Diminished Triad", 
             "context": "Classical: The 'Leading Tone' chord in C Major. Wants to resolve to C."},
            {"type": "triad", "root": "F#3", "formula_key": "dim", "instruction": "Play an F# Diminished Triad", 
             "context": "Function: The ii° chord in E Minor."},
            {"type": "triad", "root": "C#4", "formula_key": "dim", "instruction": "Play a C# Diminished Triad", 
             "context": "Function: The vii° chord in D Major."},
            {"type": "triad", "root": "G#3", "formula_key": "dim", "instruction": "Play a G# Diminished Triad", 
             "context": "Suspense: Often used in horror to create instant unease."},
            {"type": "triad", "root": "D#4", "formula_key": "dim", "instruction": "Play a D# Diminished Triad", 
             "context": "Jazz: Often found in the bridge of standards like 'All The Things You Are'."},
            {"type": "triad", "root": "A3", "formula_key": "dim", "instruction": "Play an A Diminished Triad", 
             "context": "Transition: Smoothly connects Bb Major to G Minor."},
            {"type": "triad", "root": "E4", "formula_key": "dim", "instruction": "Play an E Diminished Triad", 
             "context": "Function: The vii° chord in F Major."},
            {"type": "triad", "root": "C4", "formula_key": "dim", "instruction": "Play a C Diminished Triad", 
             "context": "Dissonance: Used for 'train wreck' moments in silent film scores."},
            {"type": "triad", "root": "F4", "formula_key": "dim", "instruction": "Play an F Diminished Triad", 
             "context": "Context: Often appears as part of a G7b9 chord."},
            {"type": "triad", "root": "G4", "formula_key": "dim", "instruction": "Play a G Diminished Triad", 
             "context": "Context: Often appears as part of an A7b9 chord."}
        ],
        "Suspended Chords": [
            {"type": "triad", "root": "C4", "formula_key": "sus4", "instruction": "Play a C Sus4 Chord", 
             "context": "Rock: 'Crazy Little Thing Called Love' (Queen) intro riff."},
            {"type": "triad", "root": "C4", "formula_key": "sus2", "instruction": "Play a C Sus2 Chord", 
             "context": "Anthem: 'Summer of 69' (Bryan Adams) arpeggiated riff."},
            {"type": "triad", "root": "G3", "formula_key": "sus4", "instruction": "Play a G Sus4 Chord", 
             "context": "Folk: 'A Hard Day's Night' (Beatles) opening chord."},
            {"type": "triad", "root": "G3", "formula_key": "sus2", "instruction": "Play a G Sus2 Chord", 
             "context": "90s Alt-Rock: 'What's Up' (4 Non Blondes)."},
            {"type": "triad", "root": "D4", "formula_key": "sus4", "instruction": "Play a D Sus4 Chord", 
             "context": "Classic Rock: 'Pinball Wizard' (The Who) strumming pattern."},
            {"type": "triad", "root": "D4", "formula_key": "sus2", "instruction": "Play a D Sus2 Chord", 
             "context": "Ballad: 'Free Fallin' (Tom Petty) uses Dsus2 to D movement."},
            {"type": "triad", "root": "A3", "formula_key": "sus4", "instruction": "Play an A Sus4 Chord", 
             "context": "Americana: 'Jack & Diane' (Mellencamp) intro."},
            {"type": "triad", "root": "A3", "formula_key": "sus2", "instruction": "Play an A Sus2 Chord", 
             "context": "Police: 'Message in a Bottle' uses stacked sus2 shapes."},
            {"type": "triad", "root": "F4", "formula_key": "sus4", "instruction": "Play an F Sus4 Chord", 
             "context": "Gospel: The 'Amen' cadence often involves a 4-3 suspension."},
            {"type": "triad", "root": "F4", "formula_key": "sus2", "instruction": "Play an F Sus2 Chord", 
             "context": "Pop: 'Someone Like You' (Adele) uses these flowing shapes."}
        ],
        "Major 7th Chords": [
            {"type": "triad", "root": "C4", "formula_key": "maj7", "instruction": "Play a C Major 7th", 
             "context": "Impressionism: 'Gymnopedie No.1' (Satie) evokes this dreamy quality."},
            {"type": "triad", "root": "F3", "formula_key": "maj7", "instruction": "Play an F Major 7th", 
             "context": "Smooth Jazz: 'Don't Know Why' (Norah Jones) relies on Bbmaj7/Fmaj7."},
            {"type": "triad", "root": "G3", "formula_key": "maj7", "instruction": "Play a G Major 7th", 
             "context": "Standard: 'Misty' (Erroll Garner) lands on this lush chord."},
            {"type": "triad", "root": "Bb3", "formula_key": "maj7", "instruction": "Play a Bb Major 7th", 
             "context": "Soul: 'What's Going On' (Marvin Gaye) uses Emaj7/Maj9 sounds."},
            {"type": "triad", "root": "Eb4", "formula_key": "maj7", "instruction": "Play an Eb Major 7th", 
             "context": "R&B: 'Best Part' (Daniel Caesar) progression."},
            {"type": "triad", "root": "Ab3", "formula_key": "maj7", "instruction": "Play an Ab Major 7th", 
             "context": "Disco: 'I Will Survive' - the 'free' chord in the progression."},
            {"type": "triad", "root": "D4", "formula_key": "maj7", "instruction": "Play a D Major 7th", 
             "context": "City Pop: 'Plastic Love' (Mariya Takeuchi) - Essential genre chord."},
            {"type": "triad", "root": "A3", "formula_key": "maj7", "instruction": "Play an A Major 7th", 
             "context": "Alt Rock: 'Under the Bridge' (RHCP) outro section."},
            {"type": "triad", "root": "E4", "formula_key": "maj7", "instruction": "Play an E Major 7th", 
             "context": "Lo-Fi Hip Hop: The quintessential 'study beat' chord."},
            {"type": "triad", "root": "Gb3", "formula_key": "maj7", "instruction": "Play a Gb Major 7th", 
             "context": "Neo-Soul: Often used by Moonchild or Hiatus Kaiyote."}
        ],
        "Minor 7th Chords": [
            {"type": "triad", "root": "D4", "formula_key": "min7", "instruction": "Play a D Minor 7th", 
             "context": "Funk: 'Get Down On It' (Kool & The Gang)."},
            {"type": "triad", "root": "G3", "formula_key": "min7", "instruction": "Play a G Minor 7th", 
             "context": "Jazz: The 'II' chord in an F Major 2-5-1 (Gm7 - C7 - Fmaj7)."},
            {"type": "triad", "root": "C4", "formula_key": "min7", "instruction": "Play a C Minor 7th", 
             "context": "Hip Hop: Nujabes style piano samples often drift through Cm7."},
            {"type": "triad", "root": "F3", "formula_key": "min7", "instruction": "Play an F Minor 7th", 
             "context": "House: Deep House chords often parallel movement of m7 chords."},
            {"type": "triad", "root": "A3", "formula_key": "min7", "instruction": "Play an A Minor 7th", 
             "context": "Classic: 'Let It Be' (Beatles) descends C -> G -> Am7."},
            {"type": "triad", "root": "E4", "formula_key": "min7", "instruction": "Play an E Minor 7th", 
             "context": "Bossa Nova: 'The Girl From Ipanema' vamp."},
            {"type": "triad", "root": "B3", "formula_key": "min7", "instruction": "Play a B Minor 7th", 
             "context": "Pop: 'Just the Way You Are' (Bruno Mars) progression."},
            {"type": "triad", "root": "F#3", "formula_key": "min7", "instruction": "Play an F# Minor 7th", 
             "context": "R&B: 'No Scrubs' (TLC) loops this chord."},
            {"type": "triad", "root": "C#4", "formula_key": "min7", "instruction": "Play a C# Minor 7th", 
             "context": "Pop: 'Sunday Morning' (Maroon 5) uses Dm7-G7-Cmaj7 (transposed)."},
            {"type": "triad", "root": "Bb3", "formula_key": "min7", "instruction": "Play a Bb Minor 7th", 
             "context": "Jazz Standard: 'Blue Bossa' opening chord."}
        ],
        "Dominant 7th Chords": [
            {"type": "triad", "root": "G3", "formula_key": "dom7", "instruction": "Play a G Dominant 7th (G7)", 
             "context": "Theory: The 'V' chord in C Major. Resolves to C."},
            {"type": "triad", "root": "C4", "formula_key": "dom7", "instruction": "Play a C Dominant 7th (C7)", 
             "context": "Funk: 'Brick House' (Commodores) main groove."},
            {"type": "triad", "root": "F3", "formula_key": "dom7", "instruction": "Play an F Dominant 7th (F7)", 
             "context": "Beatles: 'Twist and Shout' builds tension on this V chord."},
            {"type": "triad", "root": "Bb3", "formula_key": "dom7", "instruction": "Play a Bb Dominant 7th (Bb7)", 
             "context": "Jazz Blues: 'Tenor Madness' (Sonny Rollins)."},
            {"type": "triad", "root": "Eb4", "formula_key": "dom7", "instruction": "Play an Eb Dominant 7th (Eb7)", 
             "context": "Stevie Wonder: 'Superstition' clavinet vamp."},
            {"type": "triad", "root": "Ab3", "formula_key": "dom7", "instruction": "Play an Ab Dominant 7th (Ab7)", 
             "context": "R&B: Used as a secondary dominant in Eb Major."},
            {"type": "triad", "root": "D4", "formula_key": "dom7", "instruction": "Play a D Dominant 7th (D7)", 
             "context": "Folk: 'Blowin' in the Wind' (Bob Dylan)."},
            {"type": "triad", "root": "A3", "formula_key": "dom7", "instruction": "Play an A Dominant 7th (A7)", 
             "context": "Rockabilly: 'Blue Suede Shoes' stop breaks."},
            {"type": "triad", "root": "E4", "formula_key": "dom7", "instruction": "Play an E Dominant 7th (E7)", 
             "context": "Blues: The turnaround chord in A Blues (V7)."},
            {"type": "triad", "root": "B3", "formula_key": "dom7", "instruction": "Play a B Dominant 7th (B7)", 
             "context": "Beatles: 'I Saw Her Standing There' (V chord)."}
        ],
        "Half-Diminished 7th": [
            {"type": "triad", "root": "B3", "formula_key": "m7b5", "instruction": "Play a B Half-Diminished (Bø7)", 
             "context": "Jazz: 'Autumn Leaves' (in A Minor). The II chord (Bø7 - E7 - Am)."},
            {"type": "triad", "root": "E4", "formula_key": "m7b5", "instruction": "Play an E Half-Diminished (Eø7)", 
             "context": "Function: The II chord in D Minor key (Eø7 - A7 - Dm)."},
            {"type": "triad", "root": "A3", "formula_key": "m7b5", "instruction": "Play an A Half-Diminished (Aø7)", 
             "context": "Jazz: 'Autumn Leaves' (in G Minor). The II chord (Aø7 - D7 - Gm)."},
            {"type": "triad", "root": "D4", "formula_key": "m7b5", "instruction": "Play a D Half-Diminished (Dø7)", 
             "context": "Function: The II chord in C Minor key (Dø7 - G7 - Cm)."},
            {"type": "triad", "root": "G3", "formula_key": "m7b5", "instruction": "Play a G Half-Diminished (Gø7)", 
             "context": "Function: The II chord in F Minor key."},
            {"type": "triad", "root": "C4", "formula_key": "m7b5", "instruction": "Play a C Half-Diminished (Cø7)", 
             "context": "Jazz: 'Blue Bossa' transition chord (to Db Major)."},
            {"type": "triad", "root": "F#3", "formula_key": "m7b5", "instruction": "Play an F# Half-Diminished (F#ø7)", 
             "context": "Function: The II chord in E Minor key."},
            {"type": "triad", "root": "C#4", "formula_key": "m7b5", "instruction": "Play a C# Half-Diminished (C#ø7)", 
             "context": "Jazz: 'Night and Day' (Cole Porter) uses this tension."},
            {"type": "triad", "root": "F4", "formula_key": "m7b5", "instruction": "Play an F Half-Diminished (Fø7)", 
             "context": "Function: Complex passing chord in Eb Minor."},
            {"type": "triad", "root": "Bb3", "formula_key": "m7b5", "instruction": "Play a Bb Half-Diminished (Bbø7)", 
             "context": "Function: The II chord in Ab Minor key."}
        ],
        "Fully Diminished 7th": [
            {"type": "triad", "root": "B3", "formula_key": "dim7", "instruction": "Play a B Fully Diminished (B°7)", 
             "context": "Classical: Resolves strongly to C Major (vii°7)."},
            {"type": "triad", "root": "C#4", "formula_key": "dim7", "instruction": "Play a C# Fully Diminished (C#°7)", 
             "context": "Horror: 'Phantom of the Opera' uses descending chromatic dim7s."},
            {"type": "triad", "root": "D#4", "formula_key": "dim7", "instruction": "Play a D# Fully Diminished (D#°7)", 
             "context": "Silent Film: The classic 'Villain on the train tracks' chord."},
            {"type": "triad", "root": "E4", "formula_key": "dim7", "instruction": "Play an E Fully Diminished (E°7)", 
             "context": "Jazz: Passing chord between Em7 and Dm7."},
            {"type": "triad", "root": "F#3", "formula_key": "dim7", "instruction": "Play an F# Fully Diminished (F#°7)", 
             "context": "Gospel: Common passing chord resolving to G/B."},
            {"type": "triad", "root": "G#3", "formula_key": "dim7", "instruction": "Play a G# Fully Diminished (G#°7)", 
             "context": "Function: Commonly resolves to A Minor."},
            {"type": "triad", "root": "A#3", "formula_key": "dim7", "instruction": "Play an A# Fully Diminished (A#°7)", 
             "context": "Function: Passing chord in B Minor."},
            {"type": "triad", "root": "C4", "formula_key": "dim7", "instruction": "Play a C Fully Diminished (C°7)", 
             "context": "Bossa Nova: 'Corcovado' (Jobim) uses dim7s for unstable beauty."},
            {"type": "triad", "root": "D4", "formula_key": "dim7", "instruction": "Play a D Fully Diminished (D°7)", 
             "context": "Blues: 'Stormy Monday' (Allman Bros) turnaround chord."},
            {"type": "triad", "root": "F4", "formula_key": "dim7", "instruction": "Play an F Fully Diminished (F°7)", 
             "context": "Function: Chromatic passing chord."}
        ],
        "Circle of 5ths": [
            {"type": "sequence", "notes": ["C4", "F4", "Bb3"], "instruction": "Circle: Play C -> F -> Bb (Descending 5ths)", 
             "context": "Jazz: The standard motion (II-V-I) moves this way."},
            {"type": "sequence", "notes": ["Bb3", "Eb4", "Ab3"], "instruction": "Circle: Play Bb -> Eb -> Ab", 
             "context": "Gospel: Common key change direction (adding flats)."},
            {"type": "sequence", "notes": ["Ab3", "Db4", "Gb3"], "instruction": "Circle: Play Ab -> Db -> Gb", 
             "context": "R&B: Bridge progressions often cycle this way."},
            {"type": "sequence", "notes": ["Gb3", "B3", "E4"], "instruction": "Circle: Play Gb -> B -> E", 
             "context": "Modulation: Moving from 'Dark' keys to 'Bright' keys."},
            {"type": "sequence", "notes": ["E4", "A3", "D4"], "instruction": "Circle: Play E -> A -> D", 
             "context": "Rock: 'Hey Joe' (Hendrix) follows C-G-D-A-E (Ascending 5ths/Reverse). Wait, this drill is E->A->D (Descending)."},
            {"type": "sequence", "notes": ["D4", "G3", "C4"], "instruction": "Circle: Play D -> G -> C", 
             "context": "Resolution: The 'Amen Cadence' (IV-I) or V-I uses this strong pull."},
            {"type": "sequence", "notes": ["C4", "G3", "D4"], "instruction": "Reverse Circle: C -> G -> D (Ascending 5ths)", 
             "context": "Rock: 'Hey Joe' (Hendrix) moves this way (C-G-D-A-E)."},
            {"type": "sequence", "notes": ["D4", "A3", "E4"], "instruction": "Reverse Circle: D -> A -> E", 
             "context": "Country: 'Take Me Home, Country Roads' uses these bright keys."},
            {"type": "sequence", "notes": ["E4", "B3", "F#3"], "instruction": "Reverse Circle: E -> B -> F#", 
             "context": "Brightening: Adding sharps makes the music feel 'lifted'."},
            {"type": "sequence", "notes": ["F#3", "C#4", "G#3"], "instruction": "Reverse Circle: F# -> C# -> G#", 
             "context": "Modulation: Moving further into sharp keys."}
        ]
    }